swagger: "2.0"
info:
  description: "Projeto base para outros projetos"
  version: "1.0.0"
  title: "Base Project - swagger codegen"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "teste@teste.com.br"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "projectbase.swagger.io"
basePath: "/v2"

schemes:
  - "https"
  - "http"

paths:
  /pessoa:
    get:
      tags:
        - "Pessoa"
      summary: "Listar pessoa"
      operationId: "getPessoa"
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/Pessoa'

definitions:

  Pessoa:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nome:
        type: string


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"